"""wiregen: generate the TypeScript wire mirror from the Python contracts.

Design v5 §2.1 promised "message schemas: Python dataclasses + generated
TypeScript"; the wire-contract RFC §7 makes it real. The Python contract
packages are the single source of truth; this tool derives from them:

- ``web/src/lib/gen/keys.ts`` — one TS key-builder per Python key function,
  reconstructed by calling each function with placeholder tokens and
  turning the result into a template literal (arity and shape can therefore
  never drift silently: regeneration is compared in CI).
- ``web/src/lib/gen/types.ts`` — TS interfaces for every wire dataclass
  (wire field names, optionality from defaults, ns timestamps typed
  ``WireTimestamp``), the per-contract registered ``ERROR_REASONS``, the
  closed envelope ``CODES``, and ``FLOAT_FIELDS`` — which fields a
  write-side CBOR encoder must mark as floats (the reason the hand-rolled
  camera encoder existed).

Usage::

    python -m wf.tools.wiregen            # (re)write web/src/lib/gen/*.ts
    python -m wf.tools.wiregen --check    # exit 1 when committed files drift

Generated output is committed: diffs are reviewable and no build step is
required. ``pixi run wire-check`` runs the ``--check`` mode.
"""

from __future__ import annotations

import argparse
import dataclasses
import importlib
import inspect
import sys
import typing
from pathlib import Path

HEADER = (
    "// GENERATED by wf.tools.wiregen from the Python contract packages —\n"
    "// do not edit. Regenerate: `pixi run wiregen`; CI drift gate:\n"
    "// `pixi run wire-check` (wire-contract RFC §7).\n"
)

#: (tag, module) — tag prefixes the TS function names.
KEY_MODULES = [
    ("arm", "wf.contracts.arm.keys"),
    ("camera2d", "wf.contracts.camera2d.keys"),
    ("control", "wf.contracts.control.keys"),
    ("dio", "wf.contracts.dio.keys"),
    ("program", "wf.contracts.program.keys"),
    ("supervisor", "wf.contracts.supervisor.keys"),
    ("tags", "wf.contracts.tags.keys"),
    ("washer", "wf.contracts.washer.keys"),
    ("config", "wf.services.config.keys"),
    ("recording", "wf.services.recording.keys"),
]

MESSAGE_MODULES = [
    ("arm", "wf.contracts.arm.messages"),
    ("camera2d", "wf.contracts.camera2d.messages"),
    ("control", "wf.contracts.control.messages"),
    ("dio", "wf.contracts.dio.messages"),
    ("program", "wf.contracts.program.messages"),
    ("supervisor", "wf.contracts.supervisor.messages"),
    ("tags", "wf.contracts.tags.messages"),
    ("washer", "wf.contracts.washer.messages"),
]

#: params whose valid values are constrained: fallback value -> substituted
#: back out of the built key by (single) occurrence.
CONSTRAINED_PARAMS = {"command": "start"}

#: integer nanosecond fields (wire vocabulary): cbor-x may decode as BigInt.
TIMESTAMP_FIELDS = {
    "t", "t_capture", "t_data", "granted_at", "expires_at", "captured_at",
}

#: per generated-function post-processing of a parameter interpolation.
SANITIZED_PARAMS = {
    ("supervisor", "supervisor_log"): {
        "service": '${service.replace(/[/*$?#:]/g, ".")}'
    },
}


def _camel(snake: str) -> str:
    head, *rest = snake.split("_")
    return head + "".join(w.capitalize() for w in rest)


def _fn_name(tag: str, py_name: str) -> str:
    if py_name.startswith(tag + "_"):
        return _camel(py_name)
    return _camel(f"{tag}_{py_name}")


def _gen_key_fn(tag: str, name: str, fn) -> str | None:
    sig = inspect.signature(fn)
    params = list(sig.parameters.values())
    tokens: dict[str, str] = {}
    call_args: list[str] = []
    for i, p in enumerate(params):
        if p.name in CONSTRAINED_PARAMS:
            call_args.append(CONSTRAINED_PARAMS[p.name])
        else:
            token = f"ZZW{i}WZZ"
            tokens[p.name] = token
            call_args.append(token)
    try:
        built = fn(*call_args)
    except Exception as exc:  # noqa: BLE001
        print(f"wiregen: SKIP {tag}.{name}: {exc!r}", file=sys.stderr)
        return None
    template = built
    for pname, token in tokens.items():
        if template.count(token) != 1:
            print(f"wiregen: SKIP {tag}.{name}: token for {pname!r} not unique",
                  file=sys.stderr)
            return None
        interp = SANITIZED_PARAMS.get((tag, name), {}).get(pname, "${" + pname + "}")
        template = template.replace(token, interp)
    for pname, fallback in CONSTRAINED_PARAMS.items():
        if pname in sig.parameters:
            if template.count(fallback) != 1:
                print(f"wiregen: SKIP {tag}.{name}: constrained {pname!r} ambiguous",
                      file=sys.stderr)
                return None
            template = template.replace(fallback, "${" + pname + "}")
    ts_params = []
    for p in params:
        default = ""
        if p.default is not inspect.Parameter.empty and isinstance(p.default, str):
            default = f' = "{p.default}"'
        ts_params.append(f"{p.name}: string{default}")
    return (
        f"export function {_fn_name(tag, name)}({', '.join(ts_params)}): string {{\n"
        f"  return `{template}`;\n"
        f"}}\n"
    )


def gen_keys() -> str:
    out = [HEADER, "\n// One function per Python key builder; the docstring of each\n"
                   "// Python keys.py stays the normative key table.\n"]
    for tag, modname in KEY_MODULES:
        mod = importlib.import_module(modname)
        out.append(f"\n// ── {modname} ──\n")
        for name, fn in vars(mod).items():
            if not inspect.isfunction(fn) or name.startswith("_"):
                continue
            if fn.__module__ != modname:
                continue
            rendered = _gen_key_fn(tag, name, fn)
            if rendered is not None:
                out.append(rendered)
    return "".join(out)


def _ts_type(hint, own_names: set[str]) -> str:
    origin = typing.get_origin(hint)
    if origin is typing.Union or str(origin) == "<class 'types.UnionType'>":
        args = [a for a in typing.get_args(hint) if a is not type(None)]
        opt = len(args) != len(typing.get_args(hint))
        inner = " | ".join(_ts_type(a, own_names) for a in args)
        return f"{inner} | null" if opt else inner
    if origin in (list, tuple):
        args = typing.get_args(hint)
        inner = _ts_type(args[0], own_names) if args else "unknown"
        return f"{inner}[]"
    if origin is dict:
        args = typing.get_args(hint)
        val = _ts_type(args[1], own_names) if len(args) == 2 else "unknown"
        return f"Record<string, {val}>"
    if hint is int:
        return "number"
    if hint is float:
        return "number"
    if hint is str:
        return "string"
    if hint is bool:
        return "boolean"
    if hint is bytes:
        return "Uint8Array"
    if hint is dict:
        return "Record<string, unknown>"
    if hint is list:
        return "unknown[]"
    if dataclasses.is_dataclass(hint):
        return hint.__name__ if hint.__name__ in own_names else "Record<string, unknown>"
    return "unknown"


def _is_float(hint) -> bool:
    if hint is float:
        return True
    origin = typing.get_origin(hint)
    if origin is typing.Union or str(origin) == "<class 'types.UnionType'>":
        return any(a is float for a in typing.get_args(hint))
    return False


def gen_types() -> str:
    out = [HEADER,
           "\n/** Integer-nanosecond timestamps: cbor-x decodes values > 2^53 as\n"
           " *  BigInt (wire vocabulary). */\n"
           "export type WireTimestamp = number | bigint;\n"]
    float_fields: dict[str, list[str]] = {}
    for tag, modname in MESSAGE_MODULES:
        mod = importlib.import_module(modname)
        classes = [c for c in vars(mod).values()
                   if dataclasses.is_dataclass(c) and inspect.isclass(c)
                   and c.__module__ == modname]
        own_names = {c.__name__ for c in classes}
        out.append(f"\n// ── {modname} ──\n")
        for cls in classes:
            hints = typing.get_type_hints(cls)
            lines = [f"export interface {cls.__name__} {{"]
            floats: list[str] = []
            for f in dataclasses.fields(cls):
                wire_name = f.name.rstrip("_")
                hint = hints.get(f.name, None)
                if wire_name in TIMESTAMP_FIELDS and hint is int:
                    ts = "WireTimestamp"
                else:
                    ts = _ts_type(hint, own_names)
                optional = (
                    f.default is not dataclasses.MISSING
                    or f.default_factory is not dataclasses.MISSING  # type: ignore[misc]
                )
                lines.append(f"  {wire_name}{'?' if optional else ''}: {ts};")
                if _is_float(hint):
                    floats.append(wire_name)
            lines.append("}\n")
            out.append("\n".join(lines))
            if floats:
                float_fields[cls.__name__] = floats
        reasons = getattr(mod, "ERROR_REASONS", None)
        if reasons:
            const = ", ".join(f'"{r}"' for r in reasons)
            out.append(
                f"export const {tag.upper()}_ERROR_REASONS = [{const}] as const;\n"
            )
    env = importlib.import_module("wf.core.envelope")
    codes = ", ".join(f'"{c}"' for c in env.CODES)
    out.append("\n// ── wf.core.envelope ──\n")
    out.append(f"export const CODES = [{codes}] as const;\n")
    out.append(
        "\n/** Fields a write-side CBOR encoder must mark as floats (the\n"
        " *  contract types them float; whole numbers must not become ints). */\n"
    )
    out.append("export const FLOAT_FIELDS: Record<string, readonly string[]> = {\n")
    for name in sorted(float_fields):
        fields = ", ".join(f'"{f}"' for f in float_fields[name])
        out.append(f"  {name}: [{fields}],\n")
    out.append("};\n")
    return "".join(out)


def default_out_dir() -> Path:
    # packages/tools/src/wf/tools/wiregen.py -> repo platform root
    return Path(__file__).resolve().parents[5] / "web" / "src" / "lib" / "gen"


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(prog="wiregen", description=__doc__)
    parser.add_argument("--out", default=None, help="output dir (default web/src/lib/gen)")
    parser.add_argument("--check", action="store_true",
                        help="compare with committed output; exit 1 on drift")
    args = parser.parse_args(argv)
    out_dir = Path(args.out) if args.out else default_out_dir()

    files = {"keys.ts": gen_keys(), "types.ts": gen_types()}
    if args.check:
        drift = []
        for name, content in files.items():
            path = out_dir / name
            if not path.exists() or path.read_text(encoding="utf-8") != content:
                drift.append(str(path))
        if drift:
            print("wire-check FAILED — regenerate with `pixi run wiregen`:")
            for d in drift:
                print(f"  {d}")
            return 1
        print(f"wire-check OK: {len(files)} generated files match the contracts.")
        return 0

    out_dir.mkdir(parents=True, exist_ok=True)
    for name, content in files.items():
        (out_dir / name).write_text(content, encoding="utf-8", newline="\n")
        print(f"wrote {out_dir / name}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
